Repository JamesIves/github-pages-deploy-action, pull requests merged in 2021-02, with the labels that each got.

#583 Deployment Issues
  __tests__/git.test.ts
  __tests__/main.test.ts
  src/constants.ts
  src/git.ts
Labels: version 4

#584 Dev Container -> VSCode Spaces Support
  .devcontainer/Dockerfile
  .devcontainer/base.Dockerfile
  .devcontainer/devcontainer.json
Labels: version 4

#588 SSH issues
  __tests__/ssh.test.ts
  src/ssh.ts
Labels: bug, version 4

#587 Unsets Persisted Credentials
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/logo.png
  .github/screenshot.png
  .github/workflows/integration.yml
  README.md
  __tests__/git.test.ts
  __tests__/main.test.ts
  assets/icon.png
  assets/screenshot.png
  src/constants.ts
  src/git.ts
Labels: bug, version 4

#589 [Release] Version 4
  .devcontainer/Dockerfile
  .devcontainer/base.Dockerfile
  .devcontainer/devcontainer.json
  .eslintrc.json
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-beta.yml
  .github/workflows/integration.yml
  .github/workflows/production.yml
  README.md
  SECURITY.md
  __tests__/env.js
  __tests__/git.test.ts
  __tests__/main.test.ts
  __tests__/ssh.test.ts
  __tests__/util.test.ts
  __tests__/worktree.error.test.ts
  __tests__/worktree.test.ts
  action.yml
  assets/icon.png
  assets/screenshot.png
  package.json
  src/constants.ts
  src/git.ts
  src/lib.ts
  src/ssh.ts
  src/util.ts
  src/worktree.ts
  tsconfig.lint.json
Labels: release 🎉, version 4

#590 [Release] v3 Update Note
  src/lib.ts
Labels: version 3

#591 [Release] v2 Release note
  entrypoint.sh
Labels: version 2

#596 README.md: fix minor typos
  README.md
Labels: version 4
